CALTERAH_SENSOR_CONFIG_ROOT = $(CALTERAH_COMMON_ROOT)/sensor_config

CALTERAH_SENSOR_CONFIG_CSRCDIR = $(CALTERAH_SENSOR_CONFIG_ROOT)
CALTERAH_SENSOR_CONFIG_ASMSRCDIR = $(CALTERAH_SENSOR_CONFIG_ROOT)

# find all the source files in the target directories
CALTERAH_SENSOR_CONFIG_CSRCS = $(call get_csrcs, $(CALTERAH_SENSOR_CONFIG_CSRCDIR))
CALTERAH_SENSOR_CONFIG_ASMSRCS = $(call get_asmsrcs, $(CALTERAH_SENSOR_CONFIG_ASMSRCDIR))

# get object files
CALTERAH_SENSOR_CONFIG_COBJS = $(call get_relobjs, $(CALTERAH_SENSOR_CONFIG_CSRCS))
CALTERAH_SENSOR_CONFIG_ASMOBJS = $(call get_relobjs, $(CALTERAH_SENSOR_CONFIG_ASMSRCS))
CALTERAH_SENSOR_CONFIG_OBJS = $(CALTERAH_SENSOR_CONFIG_COBJS) $(CALTERAH_SENSOR_CONFIG_ASMOBJS)

# get dependency files
CALTERAH_SENSOR_CONFIG_DEPS = $(call get_deps, $(CALTERAH_SENSOR_CONFIG_OBJS))


# genearte library
CALTERAH_SENSOR_CONFIG_LIB = $(OUT_DIR)/lib_calterah_sensor_config.a

COMMON_COMPILE_PREREQUISITES += $(CALTERAH_SENSOR_CONFIG_ROOT)/sensor_config.mk

SENSOR_CONFIG_COMPILE_PREREQUISITES = $(wildcard $(CALTERAH_SENSOR_CONFIG_ROOT)/*.hxx)

# library generation rule
$(CALTERAH_SENSOR_CONFIG_LIB): $(CALTERAH_SENSOR_CONFIG_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(CALTERAH_SENSOR_CONFIG_OBJS)

# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(CALTERAH_SENSOR_CONFIG_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES) $(SENSOR_CONFIG_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $< -o $@

.SECONDEXPANSION:
$(CALTERAH_SENSOR_CONFIG_ASMOBJS): $(OUT_DIR)/%.o : %.s $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(ASM_OPT) $< -o $@

CALTERAH_COMMON_CSRC += $(CALTERAH_SENSOR_CONFIG_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(CALTERAH_SENSOR_CONFIG_ASMSRCS)

CALTERAH_COMMON_COBJS += $(CALTERAH_SENSOR_CONFIG_COBJS)
CALTERAH_COMMON_ASMOBJS += $(CALTERAH_SENSOR_CONFIG_ASMOBJS)

CALTERAH_COMMON_LIBS += $(CALTERAH_SENSOR_CONFIG_LIB)
