#ifndef _XIP_REG_H_
#define _XIP_REG_H_

#define REG_FLASH_XIP_XER_OFFSET			(0x0100)
#define REG_FLASH_XIP_XRDSRCR_OFFSET			(0x0104)
#define REG_FLASH_XIP_XRDCR_OFFSET			(0x0108)
#define REG_FLASH_XIP_XWENACR_OFFSET			(0x010C)
#define REG_FLASH_XIP_XWECR_OFFSET			(0x0110)
#define REG_FLASH_XIP_XSSCR_OFFSET			(0x0114)
#define REG_FLASH_XIP_XRDFSRCR_OFFSET			(0x0118)
#define REG_FLASH_XIP_XISOR_OFFSET			(0x011C)
#define REG_FLASH_XIP_XDSOR_OFFSET			(0x0120)

#define REG_FLASH_XIP_AMR_OFFSET			(0x0124)
#define REG_FLASH_XIP_ACDMR_OFFSET			(0x0128)
#define REG_FLASH_XIP_ARSR_OFFSET			(0x012C)
#define REG_FLASH_XIP_ATWR_OFFSET(x)			(0x0130 + ((x) << 2))

#define REG_FLASH_XIP_AVBR_OFFSET			(0x0140)
#define REG_FLASH_XIP_ALBSR_OFFSET			(0x0144)
#define REG_FLASH_XIP_AIDR_OFFSET(x)			(0x0148 + ((x) << 2))

#define REG_FLASH_XIP_AWER_OFFSET			(0x0188)
#define REG_FLASH_XIP_ANSR_OFFSET			(0x018C)
#define REG_FLASH_XIP_AIDVR_OFFSET			(0x0190)
#define REG_FLASH_XIP_ADSR_OFFSET			(0x0194)
#define REG_FLASH_XIP_AODR_OFFSET(x)			(0x0198 + ((x) << 2))

#define REG_FLASH_XIP_XABECR_OFFSET			(0x01D8)
#define REG_FLASH_XIP_XADBECR_OFFSET			(0x01DC)
#define REG_FLASH_XIP_XIBCR_OFFSET			(0x01E0)
#define REG_FLASH_XIP_XRBCR_OFFSET			(0x01E4)
#define REG_FLASH_XIP_XWBCR_OFFSET			(0x01E8)
#define REG_FLASH_XIP_XWIPCR_OFFSET			(0x01EC)
#define REG_FLASH_XIP_XXBCR_OFFSET			(0x01F0)
#define REG_FLASH_XIP_XXLCR_OFFSET			(0x01F4)
#define REG_FLASH_XIP_XEFBR_OFFSET			(0x01F8)
#define REG_FLASH_XIP_XPFBR_OFFSET			(0x01FC)


#define BITS_FLASH_XIP_CMD_INS_LEN_MASK			(0x3)
#define BITS_FLASH_XIP_CMD_INS_LEN_SHIFT		(25)
#define BITS_FLASH_XIP_CMD_ADDR_LEN_MASK		(0xF)
#define BITS_FLASH_XIP_CMD_ADDR_LEN_SHIFT		(21)
#define BITS_FLASH_XIP_CMD_DFS_MASK			(0x1F)
#define BITS_FLASH_XIP_CMD_DFS_SHIFT			(16)


#endif
