CALTERAH_CAN_CLI_ROOT = $(CALTERAH_COMMON_ROOT)/can_cli

CALTERAH_CAN_CLI_CSRCDIR = $(CALTERAH_CAN_CLI_ROOT)
CALTERAH_CAN_CLI_ASMSRCDIR = $(CALTERAH_CAN_CLI_ROOT)

# find all the source files in the target directories
CALTERAH_CAN_CLI_CSRCS = $(call get_csrcs, $(CALTERAH_CAN_CLI_CSRCDIR))
CALTERAH_CAN_CLI_ASMSRCS = $(call get_asmsrcs, $(CALTERAH_CAN_CLI_ASMSRCDIR))

# get object files
CALTERAH_CAN_CLI_COBJS = $(call get_relobjs, $(CALTERAH_CAN_CLI_CSRCS))
CALTERAH_CAN_CLI_ASMOBJS = $(call get_relobjs, $(CALTERAH_CAN_CLI_ASMSRCS))
CALTERAH_CAN_CLI_OBJS = $(CALTERAH_CAN_CLI_COBJS) $(CALTERAH_CAN_CLI_ASMOBJS)

# get dependency files
CALTERAH_CAN_CLI_DEPS = $(call get_deps, $(CALTERAH_CAN_CLI_OBJS))


# genearte library
CALTERAH_CAN_CLI_LIB = $(OUT_DIR)/lib_calterah_can_cli.a

COMMON_COMPILE_PREREQUISITES += $(CALTERAH_CAN_CLI_ROOT)/can_cli.mk

# library generation rule
$(CALTERAH_CAN_CLI_LIB): $(CALTERAH_CAN_CLI_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(CALTERAH_CAN_CLI_OBJS)

# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(CALTERAH_CAN_CLI_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $< -o $@

.SECONDEXPANSION:
$(CALTERAH_CAN_CLI_ASMOBJS): $(OUT_DIR)/%.o : %.s $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(ASM_OPT) $< -o $@

CALTERAH_COMMON_CSRC += $(CALTERAH_CAN_CLI_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(CALTERAH_CAN_CLI_ASMSRCS)

CALTERAH_COMMON_COBJS += $(CALTERAH_CAN_CLI_COBJS)
CALTERAH_COMMON_ASMOBJS += $(CALTERAH_CAN_CLI_ASMOBJS)

CALTERAH_COMMON_LIBS += $(CALTERAH_CAN_CLI_LIB)
