#ifndef _CHIP_CLOCK_H_
#define _CHIP_CLOCK_H_

#define RC_BOOT_CLOCK_FREQ		(50000000UL)
#define XTAL_CLOCK_FREQ			(50000000UL)
#define PLL0_OUTPUT_CLOCK_FREQ		(400000000UL)
#define PLL1_OUTPUT_CLOCK_FREQ		(300000000UL)

#define BUS_CLK_100M                    2
#define BUS_CLK_50M                     5

typedef enum alps_b_clock_node {
	RC_BOOT_CLOCK = 0,
	XTAL_CLOCK,
	PLL0_CLOCK,
	PLL1_CLOCK,
	SYSTEM_REF_CLOCK,
	CPU_WORK_CLOCK,
	APB_REF_CLOCK,
	APB_CLOCK,
	AHB_CLOCK,
	CPU_CLOCK,
	MEM_CLOCK,

	ROM_CLOCK,
	RAM_CLOCK,
	CAN0_CLOCK,
	CAN1_CLOCK,
	XIP_CLOCK,
	BB_CLOCK,
	UART0_CLOCK,
	UART1_CLOCK,
	I2C_CLOCK,
	SPI_M0_CLOCK,
	SPI_M1_CLOCK,
	SPI_S_CLOCK,
	QSPI_CLOCK,
	GPIO_CLOCK,
	DAC_OUT_CLOCK,
	CRC_CLOCK,
	TIMER_CLOCK,
	DMU_CLOCK,
	PWM_CLOCK
} clock_source_t;

#endif

