CALTERAH_BASEBAND_ROOT = $(CALTERAH_COMMON_ROOT)/baseband

CALTERAH_BASEBAND_CSRCDIR = $(CALTERAH_BASEBAND_ROOT)
CALTERAH_BASEBAND_ASMSRCDIR = $(CALTERAH_BASEBAND_ROOT)

# find all the source files in the target directories
CALTERAH_BASEBAND_CSRCS = $(call get_csrcs, $(CALTERAH_BASEBAND_CSRCDIR))
CALTERAH_BASEBAND_ASMSRCS = $(call get_asmsrcs, $(CALTERAH_BASEBAND_ASMSRCDIR))

# get object files
CALTERAH_BASEBAND_COBJS = $(call get_relobjs, $(CALTERAH_BASEBAND_CSRCS))
CALTERAH_BASEBAND_ASMOBJS = $(call get_relobjs, $(CALTERAH_BASEBAND_ASMSRCS))
CALTERAH_BASEBAND_OBJS = $(CALTERAH_BASEBAND_COBJS) $(CALTERAH_BASEBAND_ASMOBJS)

# get dependency files
CALTERAH_BASEBAND_DEPS = $(call get_deps, $(CALTERAH_BASEBAND_OBJS))


# genearte library
CALTERAH_BASEBAND_LIB = $(OUT_DIR)/lib_calterah_baseband.a

COMMON_COMPILE_PREREQUISITES += $(CALTERAH_BASEBAND_ROOT)/baseband.mk

# library generation rule
$(CALTERAH_BASEBAND_LIB): $(CALTERAH_BASEBAND_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(CALTERAH_BASEBAND_OBJS)

# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(CALTERAH_BASEBAND_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $(COMPILE_HW_OPT) $< -o $@

.SECONDEXPANSION:
$(CALTERAH_BASEBAND_ASMOBJS): $(OUT_DIR)/%.o : %.s $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(ASM_OPT) $(COMPILE_HW_OPT) $< -o $@

CALTERAH_COMMON_CSRC += $(CALTERAH_BASEBAND_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(CALTERAH_BASEBAND_ASMSRCS)

CALTERAH_COMMON_COBJS += $(CALTERAH_BASEBAND_COBJS)
CALTERAH_COMMON_ASMOBJS += $(CALTERAH_BASEBAND_ASMOBJS)

CALTERAH_COMMON_LIBS += $(CALTERAH_BASEBAND_LIB)
