#ifndef _ALPS_EMU_REG_H_
#define _ALPS_EMU_REG_H_

/* system. */
#define REG_EMU_SOP				(REL_REGBASE_EMU + 0x0000)
#define REG_EMU_SEC_STA				(REL_REGBASE_EMU + 0x0004)
#define REG_EMU_SEC_CTRL			(REL_REGBASE_EMU + 0x0008)
#define REG_EMU_SAFETY_PAD_CTRL			(REL_REGBASE_EMU + 0x000C)
#define REG_EMU_SAFETY_KEY1			(REL_REGBASE_EMU + 0x0010)
#define REG_EMU_SAFETY_KEY2			(REL_REGBASE_EMU + 0x0014)
#define REG_EMU_ERROR_OUT			(REL_REGBASE_EMU + 0x0018)
#define REG_EMU_SAFE_STATE			(REL_REGBASE_EMU + 0x001C)

/* FSM. */
#define REG_EMU_FSM_STA				(REL_REGBASE_EMU + 0x0100)
#define REG_EMU_WDT_ENA				(REL_REGBASE_EMU + 0x0104)
#define REG_EMU_WDT_RELOAD			(REL_REGBASE_EMU + 0x0108)
#define REG_EMU_WDT_INIT			(REL_REGBASE_EMU + 0x010C)
#define REG_EMU_WDT_VALUE			(REL_REGBASE_EMU + 0x0110)
#define REG_EMU_BOOT_DONE			(REL_REGBASE_EMU + 0x0114)
#define REG_EMU_SS1_CTRL			(REL_REGBASE_EMU + 0x0118)

/* BIST. */
#define REG_EMU_MBIST_CLK_ENA			(REL_REGBASE_EMU + 0x0200)
#define REG_EMU_GLBIST_CLK_ENA			(REL_REGBASE_EMU + 0x0204)
#define REG_EMU_BB_LBIST_CLK_ENA		(REL_REGBASE_EMU + 0x0208)
#define REG_EMU_BB_LBIST_MODE			(REL_REGBASE_EMU + 0x020C)
#define REG_EMU_BB_LBIST_ENA			(REL_REGBASE_EMU + 0x0210)
#define REG_EMU_BB_LBIST_CLR			(REL_REGBASE_EMU + 0x0214)

/* RF test. */
#define REG_EMU_RF_ERR_IRQ_ENA			(REL_REGBASE_EMU + 0x0300)
#define REG_EMU_RF_ERR_IRQ_STA			(REL_REGBASE_EMU + 0x0304)
#define REG_EMU_RF_ERR_IRQ_MASK			(REL_REGBASE_EMU + 0x0308)
#define REG_EMU_RF_ERR_SS1_ENA			(REL_REGBASE_EMU + 0x030C)
#define REG_EMU_RF_ERR_SS1_STA			(REL_REGBASE_EMU + 0x0310)
#define REG_EMU_RF_ERR_SS1_MASK			(REL_REGBASE_EMU + 0x0314)
#define REG_EMU_RF_ERR_SS2_ENA			(REL_REGBASE_EMU + 0x0318)
#define REG_EMU_RF_ERR_SS2_STA			(REL_REGBASE_EMU + 0x031C)
#define REG_EMU_RF_ERR_SS2_MASK			(REL_REGBASE_EMU + 0x0320)
#define REG_EMU_RF_TEST_ENA			(REL_REGBASE_EMU + 0x0324)
#define REG_EMU_RF_ERR_CLR			(REL_REGBASE_EMU + 0x0328)
#define REG_EMU_RF_ERR_STA			(REL_REGBASE_EMU + 0x032C)
#define REG_EMU_RF_TEST_DIV			(REL_REGBASE_EMU + 0x0330)

/* Digital test. */
#define REG_EMU_DIG_ERR_IRQ_ENA			(REL_REGBASE_EMU + 0x0400)
#define REG_EMU_DIG_ERR_IRQ_STA			(REL_REGBASE_EMU + 0x0404)
#define REG_EMU_DIG_ERR_IRQ_MASK		(REL_REGBASE_EMU + 0x0408)
#define REG_EMU_DIG_ERR_SS1_ENA			(REL_REGBASE_EMU + 0x040C)
#define REG_EMU_DIG_ERR_SS1_STA			(REL_REGBASE_EMU + 0x0410)
#define REG_EMU_DIG_ERR_SS1_MASK		(REL_REGBASE_EMU + 0x0414)
#define REG_EMU_DIG_ERR_SS2_ENA			(REL_REGBASE_EMU + 0x0418)
#define REG_EMU_DIG_ERR_SS2_STA			(REL_REGBASE_EMU + 0x041C)
#define REG_EMU_DIG_ERR_SS2_MASK		(REL_REGBASE_EMU + 0x0420)
#define REG_EMU_DIG_TEST_ENA			(REL_REGBASE_EMU + 0x0424)
#define REG_EMU_DIG_ERR_CLR			(REL_REGBASE_EMU + 0x0428)
#define REG_EMU_DIG_ERR_STA			(REL_REGBASE_EMU + 0x042C)
#define REG_EMU_DIG_TEST_DIV			(REL_REGBASE_EMU + 0x0430)

/* critical register. */
#define REG_EMU_MBIST_STA			(REL_REGBASE_EMU + 0x0500)
#define REG_EMU_LBIST_STA			(REL_REGBASE_EMU + 0x0504)
#define REG_EMU_BOOT_STA			(REL_REGBASE_EMU + 0x0508)
#define REG_EMU_REBOOT_CNT			(REL_REGBASE_EMU + 0x050C)
#define REG_EMU_REBOOT_LIMIT			(REL_REGBASE_EMU + 0x0510)
#define REG_EMU_RF_ERR_SS1_CODE0		(REL_REGBASE_EMU + 0x0514)
#define REG_EMU_RF_ERR_SS1_CODE1		(REL_REGBASE_EMU + 0x0518)
#define REG_EMU_RF_ERR_SS1_CODE2		(REL_REGBASE_EMU + 0x051C)
#define REG_EMU_RF_ERR_SS1_CODE3		(REL_REGBASE_EMU + 0x0520)
#define REG_EMU_DIG_ERR_SS1_CODE0		(REL_REGBASE_EMU + 0x0524)
#define REG_EMU_DIG_ERR_SS1_CODE1		(REL_REGBASE_EMU + 0x0528)
#define REG_EMU_DIG_ERR_SS1_CODE2		(REL_REGBASE_EMU + 0x052C)
#define REG_EMU_DIG_ERR_SS1_CODE3		(REL_REGBASE_EMU + 0x0530)
#define REG_EMU_RF_ERR_SS2_CODE			(REL_REGBASE_EMU + 0x0534)
#define REG_EMU_DIG_ERR_SS2_CODE		(REL_REGBASE_EMU + 0x0538)

/* spared register. */
#define REG_EMU_SPARED_BASE			(REL_REGBASE_EMU + 0x0600)

#endif
