#ifndef _ALPS_OTP_MMAP_H_
#define _ALPS_OTP_MMAP_H_

#define OTP_MMAP_SEC_BASE   (REL_REGBASE_EFUSE + 0x0140)
#define OTP_TRIM_AUX_ADC    (REL_REGBASE_EFUSE + 0x0158)
#define OTP_TRIM_RF_BIST    (REL_REGBASE_EFUSE + 0x015C)

#endif
