CALTERAH_CLUSTER_ROOT = $(CALTERAH_COMMON_ROOT)/cluster

CALTERAH_CLUSTER_CSRCDIR = $(CALTERAH_CLUSTER_ROOT)
CALTERAH_CLUSTER_ASMSRCDIR = $(CALTERAH_CLUSTER_ROOT)

# find all the source files in the target directories
CALTERAH_CLUSTER_CSRCS = $(call get_csrcs, $(CALTERAH_CLUSTER_CSRCDIR))
CALTERAH_CLUSTER_ASMSRCS = $(call get_asmsrcs, $(CALTERAH_CLUSTER_ASMSRCDIR))

# get object files
CALTERAH_CLUSTER_COBJS = $(call get_relobjs, $(CALTERAH_CLUSTER_CSRCS))
CALTERAH_CLUSTER_ASMOBJS = $(call get_relobjs, $(CALTERAH_CLUSTER_ASMSRCS))
CALTERAH_CLUSTER_OBJS = $(CALTERAH_CLUSTER_COBJS) $(CALTERAH_CLUSTER_ASMOBJS)

# get dependency files
CALTERAH_CLUSTER_DEPS = $(call get_deps, $(CALTERAH_CLUSTER_OBJS))


# genearte library
CALTERAH_CLUSTER_LIB = $(OUT_DIR)/lib_calterah_cluster.a

COMMON_COMPILE_PREREQUISITES += $(CALTERAH_CLUSTER_ROOT)/cluster.mk

# library generation rule
$(CALTERAH_CLUSTER_LIB): $(CALTERAH_CLUSTER_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(CALTERAH_CLUSTER_OBJS)

# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(CALTERAH_CLUSTER_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $< -o $@

.SECONDEXPANSION:
$(CALTERAH_CLUSTER_ASMOBJS): $(OUT_DIR)/%.o : %.s $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(ASM_OPT) $< -o $@

CALTERAH_COMMON_CSRC += $(CALTERAH_CLUSTER_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(CALTERAH_CLUSTER_ASMSRCS)

CALTERAH_COMMON_COBJS += $(CALTERAH_CLUSTER_COBJS)
CALTERAH_COMMON_ASMOBJS += $(CALTERAH_CLUSTER_ASMOBJS)

CALTERAH_COMMON_LIBS += $(CALTERAH_CLUSTER_LIB)
