CALTERAH_TRACK_ROOT = $(CALTERAH_COMMON_ROOT)/track

CALTERAH_TRACK_CSRCDIR = $(CALTERAH_TRACK_ROOT)
CALTERAH_TRACK_ASMSRCDIR = $(CALTERAH_TRACK_ROOT)

# 0:public 
# 1:srr 
# 2:TBD
TRK_MODE_FUNC ?= 0

# find all the source files in the target directories
CALTERAH_TRACK_CSRCS = $(call get_csrcs, $(CALTERAH_TRACK_CSRCDIR))
CALTERAH_TRACK_ASMSRCS = $(call get_asmsrcs, $(CALTERAH_TRACK_ASMSRCDIR))

# add to select the function mode
ifeq ($(TRK_MODE_FUNC),0)
CALTERAH_TRACK_CSRCS += $(CALTERAH_TRACK_ROOT)/public/ekf_track.c
endif
ifeq ($(TRK_MODE_FUNC),1)
CALTERAH_TRACK_CSRCS += $(CALTERAH_TRACK_ROOT)/solution/srr/ekf_track.c
endif

# get object files
CALTERAH_TRACK_COBJS = $(call get_relobjs, $(CALTERAH_TRACK_CSRCS))
CALTERAH_TRACK_ASMOBJS = $(call get_relobjs, $(CALTERAH_TRACK_ASMSRCS))
CALTERAH_TRACK_OBJS = $(CALTERAH_TRACK_COBJS) $(CALTERAH_TRACK_ASMOBJS)

# get dependency files
CALTERAH_TRACK_DEPS = $(call get_deps, $(CALTERAH_TRACK_OBJS))

#used to generate trackelib.a

ifeq ($(TRK_MODE_FUNC),0)
CALTERAH_TRACKLIB_CSRCDIR = $(CALTERAH_TRACK_ROOT)/public
CALTERAH_TRACKLIB_CSRCDIR = $(CALTERAH_TRACK_ROOT)/public
endif
ifeq ($(TRK_MODE_FUNC),1)
CALTERAH_TRACKLIB_CSRCDIR = $(CALTERAH_TRACK_ROOT)/solution/srr/src
CALTERAH_TRACKLIB_CSRCDIR = $(CALTERAH_TRACK_ROOT)/solution/srr/src
endif

CALTERAH_TRACKLIB_CSRCS = $(call get_csrcs, $(CALTERAH_TRACKLIB_CSRCDIR))
CALTERAH_TRACKLIB_COBJS = $(call get_relobjs, $(CALTERAH_TRACKLIB_CSRCS))
CALTERAH_TRACKLIB_DEPS = $(call get_deps, $(CALTERAH_TRACKLIB_COBJS))

ifeq ($(TRK_MODE_FUNC),0)
CALTERAH_TRACKLIB_LIB = $(CALTERAH_TRACK_CSRCDIR)/public/public_lib_calterah_tracklib_$(TOOLCHAIN).a
endif
ifeq ($(TRK_MODE_FUNC),1)
CALTERAH_TRACKLIB_LIB = $(CALTERAH_TRACK_CSRCDIR)/solution/srr/srr_lib_calterah_tracklib_$(TOOLCHAIN).a
endif

# genearte library
CALTERAH_TRACK_LIB = $(OUT_DIR)/lib_calterah_track.a

COMMON_COMPILE_PREREQUISITES += $(CALTERAH_TRACK_ROOT)/track.mk

$(CALTERAH_TRACKLIB_LIB): $(CALTERAH_TRACKLIB_COBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(TRACKLIB_AR_OPT) $@ $(CALTERAH_TRACKLIB_COBJS)

# library generation rule
$(CALTERAH_TRACK_LIB): $(CALTERAH_TRACK_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(CALTERAH_TRACK_OBJS)

ifeq ($(TRK_MODE_FUNC),1)
$(CALTERAH_TRACKLIB_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $(COMPILE_HW_OPT) $< -o $@
endif

# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(CALTERAH_TRACK_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $(COMPILE_HW_OPT) $< -o $@

.SECONDEXPANSION:
$(CALTERAH_TRACK_ASMOBJS): $(OUT_DIR)/%.o : %.s $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(ASM_OPT) $(COMPILE_HW_OPT) $< -o $@

CALTERAH_COMMON_CSRC += $(CALTERAH_TRACKLIB_CSRCS)
CALTERAH_COMMON_COBJS += $(CALTERAH_TRACKLIB_COBJS)

CALTERAH_COMMON_CSRC += $(CALTERAH_TRACK_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(CALTERAH_TRACK_ASMSRCS)

CALTERAH_COMMON_COBJS += $(CALTERAH_TRACK_COBJS)
CALTERAH_COMMON_ASMOBJS += $(CALTERAH_TRACK_ASMOBJS)

CALTERAH_COMMON_LIBS += $(CALTERAH_TRACK_LIB) $(CALTERAH_TRACKLIB_LIB)

CALTERAH_INC_DIR += $(CALTERAH_TRACK_ROOT)

ifeq ($(TRK_MODE_FUNC),0)
CALTERAH_INC_DIR += $(CALTERAH_TRACK_ROOT)/public
CALTERAH_INC_DIR += $(CALTERAH_TRACK_ROOT)/public
endif

ifeq ($(TRK_MODE_FUNC),1)
CALTERAH_INC_DIR += $(CALTERAH_TRACK_ROOT)/solution/srr/inc
CALTERAH_INC_DIR += $(CALTERAH_TRACK_ROOT)/solution/srr
endif

EXTRA_DEFINES += -DTRK_MODE_FUNC=$(TRK_MODE_FUNC)