CALTERAH_VEL_DEAMB_MF_ROOT = $(CALTERAH_COMMON_ROOT)/vel_deamb_MF

CALTERAH_VEL_DEAMB_MF_CSRCDIR = $(CALTERAH_VEL_DEAMB_MF_ROOT)
CALTERAH_VEL_DEAMB_MF_ASMSRCDIR = $(CALTERAH_VEL_DEAMB_MF_ROOT)

# find all the source files in the target directories
CALTERAH_VEL_DEAMB_MF_CSRCS = $(call get_csrcs, $(CALTERAH_VEL_DEAMB_MF_CSRCDIR))
CALTERAH_VEL_DEAMB_MF_ASMSRCS = $(call get_asmsrcs, $(CALTERAH_VEL_DEAMB_MF_ASMSRCDIR))

# get object files
CALTERAH_VEL_DEAMB_MF_COBJS = $(call get_relobjs, $(CALTERAH_VEL_DEAMB_MF_CSRCS))
CALTERAH_VEL_DEAMB_MF_ASMOBJS = $(call get_relobjs, $(CALTERAH_VEL_DEAMB_MF_ASMSRCS))
CALTERAH_VEL_DEAMB_MF_OBJS = $(CALTERAH_VEL_DEAMB_MF_COBJS) $(CALTERAH_VEL_DEAMB_MF_ASMOBJS)

# get dependency files
CALTERAH_VEL_DEAMB_MF_DEPS = $(call get_deps, $(CALTERAH_VEL_DEAMB_MF_OBJS))


# genearte library
CALTERAH_VEL_DEAMB_MF_LIB = $(OUT_DIR)/lib_calterah_vel_deamb_MF.a

COMMON_COMPILE_PREREQUISITES += $(CALTERAH_VEL_DEAMB_MF_ROOT)/vel_deamb_MF.mk

# library generation rule
$(CALTERAH_VEL_DEAMB_MF_LIB): $(CALTERAH_VEL_DEAMB_MF_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(CALTERAH_VEL_DEAMB_MF_OBJS)

# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(CALTERAH_VEL_DEAMB_MF_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $(COMPILE_HW_OPT) $< -o $@

.SECONDEXPANSION:
$(CALTERAH_VEL_DEAMB_MF_ASMOBJS): $(OUT_DIR)/%.o : %.s $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(ASM_OPT) $(COMPILE_HW_OPT) $< -o $@

CALTERAH_COMMON_CSRC += $(CALTERAH_VEL_DEAMB_MF_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(CALTERAH_VEL_DEAMB_MF_ASMSRCS)

CALTERAH_COMMON_COBJS += $(CALTERAH_VEL_DEAMB_MF_COBJS)
CALTERAH_COMMON_ASMOBJS += $(CALTERAH_VEL_DEAMB_MF_ASMOBJS)

CALTERAH_COMMON_LIBS += $(CALTERAH_VEL_DEAMB_MF_LIB)
