CALTERAH_SPI_MASTER_ROOT = $(CALTERAH_COMMON_ROOT)/spi_master

CALTERAH_SPI_MASTER_CSRCDIR = $(CALTERAH_SPI_MASTER_ROOT)
CALTERAH_SPI_MASTER_ASMSRCDIR = $(CALTERAH_SPI_MASTER_ROOT)

# find all the source files in the target directories
CALTERAH_SPI_MASTER_CSRCS = $(call get_csrcs, $(CALTERAH_SPI_MASTER_CSRCDIR))
CALTERAH_SPI_MASTER_ASMSRCS = $(call get_asmsrcs, $(CALTERAH_SPI_MASTER_ASMSRCDIR))

# get object files
CALTERAH_SPI_MASTER_COBJS = $(call get_relobjs, $(CALTERAH_SPI_MASTER_CSRCS))
CALTERAH_SPI_MASTER_ASMOBJS = $(call get_relobjs, $(CALTERAH_SPI_MASTER_ASMSRCS))
CALTERAH_SPI_MASTER_OBJS = $(CALTERAH_SPI_MASTER_COBJS) $(CALTERAH_SPI_MASTER_ASMOBJS)

# get dependency files
CALTERAH_SPI_MASTER_DEPS = $(call get_deps, $(CALTERAH_SPI_MASTER_OBJS))


# genearte library
CALTERAH_SPI_MASTER_LIB = $(OUT_DIR)/lib_spi_master.a

COMMON_COMPILE_PREREQUISITES += $(CALTERAH_SPI_MASTER_ROOT)/spi_master.mk

# library generation rule
$(CALTERAH_SPI_MASTER_LIB): $(CALTERAH_SPI_MASTER_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(CALTERAH_SPI_MASTER_OBJS)

# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(CALTERAH_SPI_MASTER_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $< -o $@


CALTERAH_COMMON_CSRC += $(CALTERAH_SPI_MASTER_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(CALTERAH_SPI_MASTER_ASMSRCS)

CALTERAH_COMMON_COBJS += $(CALTERAH_SPI_MASTER_COBJS)
CALTERAH_COMMON_ASMOBJS += $(CALTERAH_SPI_MASTER_ASMOBJS)

CALTERAH_COMMON_LIBS += $(CALTERAH_SPI_MASTER_LIB)
