#ifndef _DMU_DBG_GPIO_H_
#define _DMU_DBG_GPIO_H_

#define REL_REGBASE_DMU			(0x00BA0000U)
#define REG_GPIO_DBG_SRC		(REL_REGBASE_DMU + 0x3C)
#define REG_GPIO_DBG_VAL_OEN	(REL_REGBASE_DMU + 0x40)
#define REG_GPIO_DBG_DAT_OEN	(REL_REGBASE_DMU + 0x44)
#define REG_GPIO_DBG_DAT_O		(REL_REGBASE_DMU + 0x48)
#define REG_GPIO_DBG_DAT_I		(REL_REGBASE_DMU + 0x4c)

#endif
