CALTERAH_CASCADE_ROOT = $(CALTERAH_COMMON_ROOT)/cascade

CALTERAH_CASCADE_CSRCDIR = $(CALTERAH_CASCADE_ROOT)
CALTERAH_CASCADE_ASMSRCDIR = $(CALTERAH_CASCADE_ROOT)

# find all the source files in the target directories
CALTERAH_CASCADE_CSRCS = $(call get_csrcs, $(CALTERAH_CASCADE_CSRCDIR))
CALTERAH_CASCADE_ASMSRCS = $(call get_asmsrcs, $(CALTERAH_CASCADE_ASMSRCDIR))

# get object files
CALTERAH_CASCADE_COBJS = $(call get_relobjs, $(CALTERAH_CASCADE_CSRCS))
CALTERAH_CASCADE_ASMOBJS = $(call get_relobjs, $(CALTERAH_CASCADE_ASMSRCS))
CALTERAH_CASCADE_OBJS = $(CALTERAH_CASCADE_COBJS) $(CALTERAH_CASCADE_ASMOBJS)

# get dependency files
CALTERAH_CASCADE_DEPS = $(call get_deps, $(CALTERAH_CASCADE_OBJS))


# genearte library
CALTERAH_CASCADE_LIB = $(OUT_DIR)/lib_calterah_cascade.a

COMMON_COMPILE_PREREQUISITES += $(CALTERAH_CASCADE_ROOT)/cascade.mk

# library generation rule
$(CALTERAH_CASCADE_LIB): $(CALTERAH_CASCADE_OBJS)
	$(TRACE_ARCHIVE)
	$(Q)$(AR) $(AR_OPT) $@ $(CALTERAH_CASCADE_OBJS)

# specific compile rules
# user can add rules to compile this library
# if not rules specified to this library, it will use default compiling rules
.SECONDEXPANSION:
$(CALTERAH_CASCADE_COBJS): $(OUT_DIR)/%.o : %.c $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(COMPILE_OPT) $< -o $@

.SECONDEXPANSION:
$(CALTERAH_CASCADE_ASMOBJS): $(OUT_DIR)/%.o : %.s $$(COMMON_COMPILE_PREREQUISITES)
	$(TRACE_COMPILE)
	$(Q)$(CC) -c $(ASM_OPT) $< -o $@

CALTERAH_COMMON_CSRC += $(CALTERAH_CASCADE_CSRCS)
CALTERAH_COMMON_ASMSRCS += $(CALTERAH_CASCADE_ASMSRCS)

CALTERAH_COMMON_COBJS += $(CALTERAH_CASCADE_COBJS)
CALTERAH_COMMON_ASMOBJS += $(CALTERAH_CASCADE_ASMOBJS)

CALTERAH_COMMON_LIBS += $(CALTERAH_CASCADE_LIB)
